import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Home(),
        ]),
      ),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
    Container(
  width: 375,
  height: 812,
  clipBehavior: Clip.hardEdge,
  decoration: const BoxDecoration(
    color: Color(0xFFF7F6F4),
  ),
  child: SizedBox(
    width: double.infinity,
    child: Stack(
      clipBehavior: Clip.none,
      children: [
        Positioned(
          left: 24,
          top: 136,
          child: Container(
            width: 327,
            height: 144,
            clipBehavior: Clip.hardEdge,
            decoration: BoxDecoration(
              color: const Color(0xFFFCFCFC),
              borderRadius: BorderRadius.circular(20),
              boxShadow: const [
                BoxShadow(
                  color: Color(0x112020A1),
                  spreadRadius: 0,
                  offset: Offset(4, 6),
                  blurRadius: 25,
                )
              ],
            ),
          ),
        ),
        Positioned(
          left: 219,
          top: 257,
          child: Image.network(
            'https://storage.googleapis.com/codeless-dev.appspot.com/uploads%2Fimages%2FpK63IaA0mAbtjrVI7cPv%2F5fb4f8c74986df392277de856ea0ad12.png',
            width: 119,
            height: 11,
            fit: BoxFit.contain,
          ),
        ),
        Positioned(
          left: 224,
          top: 194,
          child: Image.network(
            'https://storage.googleapis.com/codeless-dev.appspot.com/uploads%2Fimages%2FpK63IaA0mAbtjrVI7cPv%2F3305ef5c46ad883b08225b4e10f81153.png',
            width: 112,
            height: 63,
            fit: BoxFit.contain,
          ),
        ),
        Positioned(
          left: 231,
          top: 232,
          child: Image.network(
            'https://storage.googleapis.com/codeless-dev.appspot.com/uploads%2Fimages%2FpK63IaA0mAbtjrVI7cPv%2F284cbc4f6c928509e897c00539c9eeb1.png',
            width: 31,
            height: 23,
            fit: BoxFit.contain,
          ),
        ),
        Positioned(
          left: 224,
          top: 242,
          child: Image.network(
            'https://storage.googleapis.com/codeless-dev.appspot.com/uploads%2Fimages%2FpK63IaA0mAbtjrVI7cPv%2F4249f3b79f6942962230f2020fc48e3a.png',
            width: 112,
            height: 15,
            fit: BoxFit.contain,
          ),
        ),
        Positioned(
          left: 277,
          top: 166,
          child: Image.network(
            'https://storage.googleapis.com/codeless-dev.appspot.com/uploads%2Fimages%2FpK63IaA0mAbtjrVI7cPv%2F0cb915529ad270641a17e253423a7db5.png',
            width: 34,
            height: 99,
            fit: BoxFit.contain,
          ),
        ),
        Positioned(
          left: 292,
          top: 213,
          child: Image.network(
            'https://storage.googleapis.com/codeless-dev.appspot.com/uploads%2Fimages%2FpK63IaA0mAbtjrVI7cPv%2F37a8e0ed5538ee00d5b8653c318196d4.png',
            width: 4,
            height: 5,
            fit: BoxFit.contain,
          ),
        ),
        Positioned(
          left: 247,
          top: 164,
          child: Image.network(
            'https://storage.googleapis.com/codeless-dev.appspot.com/uploads%2Fimages%2FpK63IaA0mAbtjrVI7cPv%2F2284960f9e7cbeb14ba231694cf4e3f8.png',
            width: 36,
            height: 102,
            fit: BoxFit.contain,
          ),
        ),
        Positioned(
          left: 229,
          top: 148,
          child: Image.network(
            'https://storage.googleapis.com/codeless-dev.appspot.com/uploads%2Fimages%2FpK63IaA0mAbtjrVI7cPv%2F13ccb9951ebae887195346db68a7297b.png',
            width: 95,
            height: 42,
            fit: BoxFit.contain,
          ),
        ),
        Positioned(
          left: 39,
          top: 188,
          child: Text(
            'Let’s Find A \nGuide For You.',
            style: GoogleFonts.getFont(
              'Poppins',
              color: const Color(0xFF36314F),
              fontSize: 18,
              fontWeight: FontWeight.bold,
              height: 1.2,
            ),
          ),
        ),
        Positioned(
          left: 172,
          top: 258,
          child: Container(
            width: 6,
            height: 6,
            clipBehavior: Clip.hardEdge,
            decoration: BoxDecoration(
              color: const Color(0x7F4CCB70),
              borderRadius: BorderRadius.circular(3),
            ),
          ),
        ),
        Positioned(
          left: 184,
          top: 258,
          child: Container(
            width: 6,
            height: 6,
            clipBehavior: Clip.hardEdge,
            decoration: BoxDecoration(
              color: const Color(0xFF4CCB70),
              borderRadius: BorderRadius.circular(3),
            ),
          ),
        ),
        Positioned(
          left: 196,
          top: 258,
          child: Container(
            width: 6,
            height: 6,
            clipBehavior: Clip.hardEdge,
            decoration: BoxDecoration(
              color: const Color(0x7F4CCB70),
              borderRadius: BorderRadius.circular(3),
            ),
          ),
        ),
        Positioned(
          left: 305,
          top: 66,
          child: Container(
            width: 46,
            height: 46,
            clipBehavior: Clip.hardEdge,
            decoration: BoxDecoration(
              color: Colors.white,
              borderRadius: BorderRadius.circular(10),
              boxShadow: const [
                BoxShadow(
                  color: Color(0x0C000000),
                  spreadRadius: 0,
                  offset: Offset(2, 6),
                  blurRadius: 15,
                )
              ],
            ),
          ),
        ),
        Positioned(
          left: 317,
          top: 78,
          child: Image.network(
            'https://storage.googleapis.com/codeless-dev.appspot.com/uploads%2Fimages%2FpK63IaA0mAbtjrVI7cPv%2F52089afe79e81cf9c7723c30cd2773fd.png',
            width: 21,
            height: 22,
            fit: BoxFit.contain,
          ),
        ),
        Positioned(
          left: 243,
          top: 66,
          child: Container(
            width: 46,
            height: 46,
            clipBehavior: Clip.hardEdge,
            decoration: BoxDecoration(
              color: Colors.white,
              borderRadius: BorderRadius.circular(10),
              boxShadow: const [
                BoxShadow(
                  color: Color(0x0C000000),
                  spreadRadius: 0,
                  offset: Offset(2, 6),
                  blurRadius: 15,
                )
              ],
            ),
          ),
        ),
        Positioned(
          left: 256,
          top: 78,
          child: Image.network(
            'https://storage.googleapis.com/codeless-dev.appspot.com/uploads%2Fimages%2FpK63IaA0mAbtjrVI7cPv%2Fe178d5a6a1571816e84630396e6e55de.png',
            width: 19,
            height: 22,
            fit: BoxFit.contain,
          ),
        ),
        Positioned(
          left: 24,
          top: 66,
          child: Container(
            width: 46,
            height: 46,
            clipBehavior: Clip.hardEdge,
            decoration: BoxDecoration(
              color: Colors.white,
              borderRadius: BorderRadius.circular(10),
              boxShadow: const [
                BoxShadow(
                  color: Color(0x0C000000),
                  spreadRadius: 0,
                  offset: Offset(2, 6),
                  blurRadius: 15,
                )
              ],
            ),
          ),
        ),
        Positioned(
          left: 26,
          top: 68,
          child: Container(
            width: 42,
            height: 42,
            clipBehavior: Clip.hardEdge,
            decoration: BoxDecoration(
              image: const DecorationImage(
                image: NetworkImage(
                  'https://firebasestorage.googleapis.com/v0/b/codeless-app.appspot.com/o/projects%2FpK63IaA0mAbtjrVI7cPv%2F170bdc492b08d828d4063c7b929e2ccf9274c3f2Image.png?alt=media&token=2652e99a-24b0-4557-8c65-e20e6c4156c5',
                ),
                fit: BoxFit.cover,
              ),
              borderRadius: BorderRadius.circular(10),
              boxShadow: const [
                BoxShadow(
                  color: Color(0x0C000000),
                  spreadRadius: 0,
                  offset: Offset(2, 6),
                  blurRadius: 15,
                )
              ],
            ),
          ),
        ),
        Positioned(
          left: 350,
          top: 32,
          child: Image.network(
            'https://storage.googleapis.com/codeless-dev.appspot.com/uploads%2Fimages%2FpK63IaA0mAbtjrVI7cPv%2F766eb113169ff26feafb5bc567c36b56.png',
            width: 1,
            height: 4,
            fit: BoxFit.contain,
          ),
        ),
        Positioned(
          left: 0,
          top: 316,
          child: Container(
            width: 375,
            height: 1172,
            clipBehavior: Clip.hardEdge,
            decoration: const BoxDecoration(
              color: Color(0xFFFCFCFC),
              borderRadius: BorderRadius.vertical(
                top: Radius.circular(20),
              ),
            ),
          ),
        ),
        Positioned(
          left: 24,
          top: 721,
          child: Container(
            width: 89,
            height: 30,
            clipBehavior: Clip.hardEdge,
            decoration: BoxDecoration(
              color: const Color(0xFF289B7E),
              borderRadius: BorderRadius.circular(10),
            ),
          ),
        ),
        Positioned(
          left: 41,
          top: 726,
          child: Text(
            'Nearest ',
            style: GoogleFonts.getFont(
              'Space Grotesk',
              color: const Color(0xFFF9F9FB),
              fontSize: 14,
            ),
          ),
        ),
        Positioned(
          left: 136,
          top: 726,
          child: Text(
            'Popular',
            style: GoogleFonts.getFont(
              'Space Grotesk',
              color: const Color(0xFF36314F),
              fontSize: 14,
            ),
          ),
        ),
        Positioned(
          left: 212,
          top: 726,
          child: Text(
            'Hotest',
            style: GoogleFonts.getFont(
              'Space Grotesk',
              color: const Color(0xFF36314F),
              fontSize: 14,
            ),
          ),
        ),
        Positioned(
          left: 282,
          top: 726,
          child: Text(
            'Based Location',
            style: GoogleFonts.getFont(
              'Space Grotesk',
              color: const Color(0xFF36314F),
              fontSize: 14,
            ),
          ),
        ),
        Positioned(
          left: 271,
          top: 865,
          child: Container(
            width: 80,
            height: 74,
            clipBehavior: Clip.hardEdge,
            decoration: BoxDecoration(
              color: const Color(0xFFF7F6F4),
              borderRadius: BorderRadius.circular(20),
            ),
          ),
        ),
        Positioned(
          left: 120,
          top: 908,
          child: Image.network(
            'https://storage.googleapis.com/codeless-dev.appspot.com/uploads%2Fimages%2FpK63IaA0mAbtjrVI7cPv%2Fd6821e1a981d6f42346a7d0cc7037aa9.png',
            width: 12,
            height: 12,
            fit: BoxFit.contain,
          ),
        ),
        Positioned(
          left: 139,
          top: 905,
          child: Text(
            '4.6',
            style: GoogleFonts.getFont(
              'Poppins',
              color: const Color(0xFF4CCB70),
              fontSize: 12,
            ),
          ),
        ),
        Positioned(
          left: 23,
          top: 905,
          child: Text(
            '0.5 Mil Away',
            style: GoogleFonts.getFont(
              'Poppins',
              color: const Color(0xFF289B7E),
              fontSize: 12,
            ),
          ),
        ),
        Positioned(
          left: 23,
          top: 879,
          child: SizedBox(
            width: 222,
            child: Text(
              'Shemar Valley, Denpasar',
              style: GoogleFonts.getFont(
                'Space Grotesk',
                color: const Color(0xFF36314F),
                fontSize: 16,
              ),
            ),
          ),
        ),
        Positioned(
          left: 200,
          top: 905,
          child: Text(
            '178K',
            style: GoogleFonts.getFont(
              'Poppins',
              color: const Color(0xFF4CCB70),
              fontSize: 12,
            ),
          ),
        ),
        Positioned(
          left: 181,
          top: 908,
          child: Image.network(
            'https://storage.googleapis.com/codeless-dev.appspot.com/uploads%2Fimages%2FpK63IaA0mAbtjrVI7cPv%2F44cdf7095022561a397e1a2e812511ca.png',
            width: 12,
            height: 12,
            fit: BoxFit.contain,
          ),
        ),
        Positioned(
          left: 271,
          top: 775,
          child: Container(
            width: 80,
            height: 74,
            clipBehavior: Clip.hardEdge,
            decoration: BoxDecoration(
              color: const Color(0xFFF7F6F4),
              borderRadius: BorderRadius.circular(20),
            ),
          ),
        ),
        Positioned(
          left: 120,
          top: 818,
          child: Image.network(
            'https://storage.googleapis.com/codeless-dev.appspot.com/uploads%2Fimages%2FpK63IaA0mAbtjrVI7cPv%2Fd6821e1a981d6f42346a7d0cc7037aa9.png',
            width: 12,
            height: 12,
            fit: BoxFit.contain,
          ),
        ),
        Positioned(
          left: 139,
          top: 815,
          child: Text(
            '4.6',
            style: GoogleFonts.getFont(
              'Poppins',
              color: const Color(0xFF4CCB70),
              fontSize: 12,
            ),
          ),
        ),
        Positioned(
          left: 23,
          top: 815,
          child: Text(
            '0.3 Mil Away',
            style: GoogleFonts.getFont(
              'Poppins',
              color: const Color(0xFF289B7E),
              fontSize: 12,
            ),
          ),
        ),
        Positioned(
          left: 23,
          top: 789,
          child: SizedBox(
            width: 222,
            child: Text(
              'Marian Beach, Yogyakarta',
              style: GoogleFonts.getFont(
                'Space Grotesk',
                color: const Color(0xFF36314F),
                fontSize: 16,
              ),
            ),
          ),
        ),
        Positioned(
          left: 200,
          top: 815,
          child: Text(
            '178K',
            style: GoogleFonts.getFont(
              'Poppins',
              color: const Color(0xFF4CCB70),
              fontSize: 12,
            ),
          ),
        ),
        Positioned(
          left: 181,
          top: 818,
          child: Image.network(
            'https://storage.googleapis.com/codeless-dev.appspot.com/uploads%2Fimages%2FpK63IaA0mAbtjrVI7cPv%2F44cdf7095022561a397e1a2e812511ca.png',
            width: 12,
            height: 12,
            fit: BoxFit.contain,
          ),
        ),
        Positioned(
          left: 312,
          top: 659,
          child: Text(
            'Foods',
            textAlign: TextAlign.center,
            style: GoogleFonts.getFont(
              'Poppins',
              color: const Color(0xFF36314F),
              fontSize: 10,
              fontWeight: FontWeight.w500,
            ),
          ),
        ),
        Positioned(
          left: 305,
          top: 604,
          child: Container(
            width: 46,
            height: 46,
            clipBehavior: Clip.hardEdge,
            decoration: BoxDecoration(
              color: Colors.white,
              borderRadius: BorderRadius.circular(10),
              boxShadow: const [
                BoxShadow(
                  color: Color(0x0C000000),
                  spreadRadius: 0,
                  offset: Offset(2, 6),
                  blurRadius: 15,
                )
              ],
            ),
          ),
        ),
        Positioned(
          left: 319,
          top: 616,
          child: Image.network(
            'https://storage.googleapis.com/codeless-dev.appspot.com/uploads%2Fimages%2FpK63IaA0mAbtjrVI7cPv%2Fdc32e42ee1a11aaa77ad0eca6fff4a56.png',
            width: 18,
            height: 22,
            fit: BoxFit.contain,
          ),
        ),
        Positioned(
          left: 225,
          top: 659,
          child: Text(
            'Cars',
            textAlign: TextAlign.center,
            style: GoogleFonts.getFont(
              'Poppins',
              color: const Color(0xFF36314F),
              fontSize: 10,
              fontWeight: FontWeight.w500,
            ),
          ),
        ),
        Positioned(
          left: 215,
          top: 604,
          child: Container(
            width: 46,
            height: 46,
            clipBehavior: Clip.hardEdge,
            decoration: BoxDecoration(
              color: Colors.white,
              borderRadius: BorderRadius.circular(10),
              boxShadow: const [
                BoxShadow(
                  color: Color(0x0C000000),
                  spreadRadius: 0,
                  offset: Offset(2, 6),
                  blurRadius: 15,
                )
              ],
            ),
          ),
        ),
        Positioned(
          left: 224,
          top: 616,
          child: Image.network(
            'https://storage.googleapis.com/codeless-dev.appspot.com/uploads%2Fimages%2FpK63IaA0mAbtjrVI7cPv%2F8f94e1b7a270d242862ed932502a83be.png',
            width: 28,
            height: 22,
            fit: BoxFit.contain,
          ),
        ),
        Positioned(
          left: 120,
          top: 659,
          child: Text(
            'Hotels',
            textAlign: TextAlign.center,
            style: GoogleFonts.getFont(
              'Poppins',
              color: const Color(0xFF36314F),
              fontSize: 10,
              fontWeight: FontWeight.w500,
            ),
          ),
        ),
        Positioned(
          left: 114,
          top: 604,
          child: Container(
            width: 46,
            height: 46,
            clipBehavior: Clip.hardEdge,
            decoration: BoxDecoration(
              color: Colors.white,
              borderRadius: BorderRadius.circular(10),
              boxShadow: const [
                BoxShadow(
                  color: Color(0x0C000000),
                  spreadRadius: 0,
                  offset: Offset(2, 6),
                  blurRadius: 15,
                )
              ],
            ),
          ),
        ),
        Positioned(
          left: 126,
          top: 616,
          child: Image.network(
            'https://storage.googleapis.com/codeless-dev.appspot.com/uploads%2Fimages%2FpK63IaA0mAbtjrVI7cPv%2Ff10e1fc2891fcb733820c07fc4abafd1.png',
            width: 21,
            height: 22,
            fit: BoxFit.contain,
          ),
        ),
        Positioned(
          left: 30,
          top: 659,
          child: Text(
            'Events',
            textAlign: TextAlign.center,
            style: GoogleFonts.getFont(
              'Poppins',
              color: const Color(0xFF36314F),
              fontSize: 10,
              fontWeight: FontWeight.w500,
            ),
          ),
        ),
        Positioned(
          left: 24,
          top: 604,
          child: Container(
            width: 46,
            height: 46,
            clipBehavior: Clip.hardEdge,
            decoration: BoxDecoration(
              color: Colors.white,
              borderRadius: BorderRadius.circular(10),
              boxShadow: const [
                BoxShadow(
                  color: Color(0x0C000000),
                  spreadRadius: 0,
                  offset: Offset(2, 6),
                  blurRadius: 15,
                )
              ],
            ),
          ),
        ),
        Positioned(
          left: 36,
          top: 616,
          child: Image.network(
            'https://storage.googleapis.com/codeless-dev.appspot.com/uploads%2Fimages%2FpK63IaA0mAbtjrVI7cPv%2Fa96401d142872be0f4082892479546a0.png',
            width: 22,
            height: 22,
            fit: BoxFit.contain,
          ),
        ),
        Positioned(
          left: 312,
          top: 565,
          child: Text(
            'Opps!',
            textAlign: TextAlign.center,
            style: GoogleFonts.getFont(
              'Poppins',
              color: const Color(0xFF36314F),
              fontSize: 10,
              fontWeight: FontWeight.w500,
            ),
          ),
        ),
        Positioned(
          left: 305,
          top: 510,
          child: Container(
            width: 46,
            height: 46,
            clipBehavior: Clip.hardEdge,
            decoration: BoxDecoration(
              color: Colors.white,
              borderRadius: BorderRadius.circular(10),
              boxShadow: const [
                BoxShadow(
                  color: Color(0x0C000000),
                  spreadRadius: 0,
                  offset: Offset(2, 6),
                  blurRadius: 15,
                )
              ],
            ),
          ),
        ),
        Positioned(
          left: 319,
          top: 522,
          child: Image.network(
            'https://storage.googleapis.com/codeless-dev.appspot.com/uploads%2Fimages%2FpK63IaA0mAbtjrVI7cPv%2Fdc32e42ee1a11aaa77ad0eca6fff4a56.png',
            width: 18,
            height: 22,
            fit: BoxFit.contain,
          ),
        ),
        Positioned(
          left: 209,
          top: 565,
          child: Text(
            'Something',
            textAlign: TextAlign.center,
            style: GoogleFonts.getFont(
              'Poppins',
              color: const Color(0xFF36314F),
              fontSize: 10,
              fontWeight: FontWeight.w500,
            ),
          ),
        ),
        Positioned(
          left: 215,
          top: 510,
          child: Container(
            width: 46,
            height: 46,
            clipBehavior: Clip.hardEdge,
            decoration: BoxDecoration(
              color: Colors.white,
              borderRadius: BorderRadius.circular(10),
              boxShadow: const [
                BoxShadow(
                  color: Color(0x0C000000),
                  spreadRadius: 0,
                  offset: Offset(2, 6),
                  blurRadius: 15,
                )
              ],
            ),
          ),
        ),
        Positioned(
          left: 224,
          top: 522,
          child: Image.network(
            'https://storage.googleapis.com/codeless-dev.appspot.com/uploads%2Fimages%2FpK63IaA0mAbtjrVI7cPv%2F8f94e1b7a270d242862ed932502a83be.png',
            width: 28,
            height: 22,
            fit: BoxFit.contain,
          ),
        ),
        Positioned(
          left: 118,
          top: 565,
          child: Text(
            'Explore',
            textAlign: TextAlign.center,
            style: GoogleFonts.getFont(
              'Poppins',
              color: const Color(0xFF36314F),
              fontSize: 10,
              fontWeight: FontWeight.w500,
            ),
          ),
        ),
        Positioned(
          left: 114,
          top: 510,
          child: Container(
            width: 46,
            height: 46,
            clipBehavior: Clip.hardEdge,
            decoration: BoxDecoration(
              color: Colors.white,
              borderRadius: BorderRadius.circular(10),
              boxShadow: const [
                BoxShadow(
                  color: Color(0x0C000000),
                  spreadRadius: 0,
                  offset: Offset(2, 6),
                  blurRadius: 15,
                )
              ],
            ),
          ),
        ),
        Positioned(
          left: 126,
          top: 522,
          child: Image.network(
            'https://storage.googleapis.com/codeless-dev.appspot.com/uploads%2Fimages%2FpK63IaA0mAbtjrVI7cPv%2Ff10e1fc2891fcb733820c07fc4abafd1.png',
            width: 21,
            height: 22,
            fit: BoxFit.contain,
          ),
        ),
        Positioned(
          left: 14,
          top: 565,
          child: Text(
            'Local Guides',
            textAlign: TextAlign.center,
            style: GoogleFonts.getFont(
              'Poppins',
              color: const Color(0xFF36314F),
              fontSize: 10,
              fontWeight: FontWeight.w500,
            ),
          ),
        ),
        Positioned(
          left: 24,
          top: 510,
          child: Container(
            width: 46,
            height: 46,
            clipBehavior: Clip.hardEdge,
            decoration: BoxDecoration(
              color: Colors.white,
              borderRadius: BorderRadius.circular(10),
              boxShadow: const [
                BoxShadow(
                  color: Color(0x0C000000),
                  spreadRadius: 0,
                  offset: Offset(2, 6),
                  blurRadius: 15,
                )
              ],
            ),
          ),
        ),
        Positioned(
          left: 36,
          top: 522,
          child: Image.network(
            'https://storage.googleapis.com/codeless-dev.appspot.com/uploads%2Fimages%2FpK63IaA0mAbtjrVI7cPv%2Fa96401d142872be0f4082892479546a0.png',
            width: 22,
            height: 22,
            fit: BoxFit.contain,
          ),
        ),
        Positioned(
          left: 23,
          top: 470,
          child: Text(
            'Chose Categories',
            style: GoogleFonts.getFont(
              'Montserrat',
              color: const Color(0xFF36314F),
              fontSize: 18,
              fontWeight: FontWeight.bold,
            ),
          ),
        ),
        Positioned(
          left: 24,
          top: 401,
          child: Container(
            width: 327,
            height: 46,
            clipBehavior: Clip.hardEdge,
            decoration: BoxDecoration(
              color: const Color(0xFFF7F6F4),
              borderRadius: BorderRadius.circular(10),
            ),
          ),
        ),
        Positioned(
          left: 41,
          top: 414,
          child: Text(
            'Search',
            style: GoogleFonts.getFont(
              'Poppins',
              color: const Color(0xFF36314F),
              fontSize: 12,
            ),
          ),
        ),
        Positioned(
          left: 321,
          top: 416,
          child: Image.network(
            'https://storage.googleapis.com/codeless-dev.appspot.com/uploads%2Fimages%2FpK63IaA0mAbtjrVI7cPv%2F6f9b68a2823e7faa6de326fc15103d6d.png',
            width: 16,
            height: 16,
            fit: BoxFit.contain,
          ),
        ),
        Positioned(
          left: 317,
          top: 355,
          child: Image.network(
            'https://storage.googleapis.com/codeless-dev.appspot.com/uploads%2Fimages%2FpK63IaA0mAbtjrVI7cPv%2F55cfafaf9feb12f9143b934714b8d44b.png',
            width: 24,
            height: 21,
            fit: BoxFit.contain,
          ),
        ),
        Positioned(
          left: 23,
          top: 339,
          child: Text(
            'Your Location',
            style: GoogleFonts.getFont(
              'Poppins',
              color: const Color(0xFF36314F),
              fontSize: 12,
            ),
          ),
        ),
        Positioned(
          left: 23,
          top: 359,
          child: Text(
            'Birtamode, Nepal',
            style: GoogleFonts.getFont(
              'Montserrat',
              color: const Color(0xFF4CCB70),
              fontSize: 18,
              fontWeight: FontWeight.bold,
            ),
          ),
        ),
        Positioned(
          left: 198,
          top: 368,
          child: Image.network(
            'https://storage.googleapis.com/codeless-dev.appspot.com/uploads%2Fimages%2FpK63IaA0mAbtjrVI7cPv%2F4d956fb984d7f4834439c3e93f7c95e4.png',
            width: 10,
            height: 6,
            fit: BoxFit.contain,
          ),
        ),
        Positioned(
          left: 247,
          top: 72,
          child: Container(
            width: 24,
            height: 24,
            clipBehavior: Clip.hardEdge,
            decoration: const BoxDecoration(),
            child: Stack(
              clipBehavior: Clip.none,
              children: [
                Positioned(
                  left: 3,
                  top: 2,
                  child: Image.network(
                    'https://storage.googleapis.com/codeless-dev.appspot.com/uploads%2Fimages%2FpK63IaA0mAbtjrVI7cPv%2F883b7d843d25a8328489b277d8467399.png',
                    width: 18,
                    height: 19,
                    fit: BoxFit.contain,
                  ),
                )
              ],
            ),
          ),
        )
      ],
    ),
  ),
)
      ],
    );
  }
}